/*
 * This source file was generated by the Gradle 'init' task
 */
package pokedexproject;

import org.junit.jupiter.api.Test;

import pokedexproject.controller.Runner;

import static org.junit.jupiter.api.Assertions.*;

@SuppressWarnings("unused")
class AppTest {
    @Test void appHasAGreeting() {
        Runner classUnderTest = new Runner();
    }
}
